# Set the name of your application:
APPLICATION = context_switching
# If no BOARD is found in the environment, use this default:
# BOARD ?= nucleo-f401re
BOARD ?= native

USEMODULE += xtimer
# This has to be the absolute path to the RIOT base directory:
RIOTBASE ?= $(CURDIR)/../os/riot
include $(RIOTBASE)/Makefile.include